### ISSUE TITLE
Quasar Startup failed

### ISSUE THREAD

**Issue by WHITE-AIRSPACE** [quasarframework/quasar-awesome#123]
`quasar dev`

` error  in `./.quasar/app.styl`

`Module build failed (from ./node_modules/stylus-loader/index.js):`
  `Error: /home/white/WebstormProjects/xxxxx/.quasar/app.styl:9:9`
    `  5|  * Edit /src/css/themes instead`
    `  6|  **/`
    `  7| `
      `8| // First we load app's Stylus variables`
    `  9| @import '~quasar-app-variables'`
  `--------------^`
    ` 10| `
    ` 11| // Then we load Quasar stylus files`
     `12| @import '~quasar-styl'`
  `failed to locate @import file ~quasar-app-variables.styl`
  
  `- evaluator.js:157 CachedPathEvaluator.visitImport`
  `  [xxxxx]/[stylus-loader]/lib/evaluator.js:157:21
`

**Comment by genyded** [comment]
Same here.

**Comment by caiman90** [comment]
anybody resolved this one ?

**Comment by rstoenescu** [comment]
Wrong repo to report this to.
Also, there's absolutely no information on how you're using Quasar. This is definitely a problem in your setup, not a Quasar issue.
