### ISSUE TITLE
list update procedure

### ISSUE THREAD

**Issue by erhanturan** [quasarframework/quasar-awesome#134]
Hello,

Absolutely dummy question: How do I update the list? Like to add our own project so I  downloaded the repo and committed locally but cannot push to remote. I'm not familiar with the workflow to be honest. Any advice?

Thanks,
Erhan

**Comment by dmitry** [comment]
@erhanturan it's really simple. Go to: https://github.com/quasarframework/quasar-awesome/blob/master/README.md click on pencil (edit) and that's it. Then just push pull request so it could be merged.

**Comment by erhanturan** [comment]
Thanks @dmitry ! I was naively trying to push git updates :)
