### ISSUE TITLE
Broken Link in README

### ISSUE THREAD

**Issue by athix** [quasarframework/quasar-awesome#254]
It appears that @dannyconnell's link (https://dannys.link/quasarf) is currently broken. The link shortening service displays the following warning:

<img src="https://user-images.githubusercontent.com/1802598/147517397-27c9715c-7669-4554-adaf-0768df12e816.png" width="250px" alt="Screenshot of Link not found error">

**Comment by rstoenescu** [comment]
@dannyconnell can you take a look and see why the link doesn't works anymore? Do you want us to change the link to something else?

**Comment by dannyconnell** [comment]
@rstoenescu @athix if you remove the “f” at the end it should work:

https://dannys.link/quasar[https://dannys.link/quasar](https://dannys.link/quasar)

**Comment by athix** [comment]
Can confirm that the link works without the trailing f.

@dannyconnell looks like it links to a course on Quasar v1. If you have one for v2, it would be worth adding that and distinguishing between the two for those who have yet to upgrade to Quasar v2 / Vue 3.

(Also your YouTube videos were helpful when I was getting started, so thank you! The music loop was getting on my nerves by the end, but your presenting style is very concise and understandable. 😊)

**Comment by rstoenescu** [comment]
Thanks! Updated
