### ISSUE TITLE
Spanish telegram group

### ISSUE THREAD

**Issue by eliecer2000** [quasarframework/quasar-awesome#266]
Hello, I am the administrator of the "Quasar en Español" group in telegram, in this channel we share experiences, issues, and any valuable information about Quasar Framework.

We already have time connected, and I would like to know if it is possible to share the link of the group so that our community in Spanish grows, and so we can help more people.

Our link is [(https://t.me/quasarframework_es](https://t.me/quasarframework_es)

I remain attentive to your answer

thank you.

**Comment by rstoenescu** [comment]
Hi,

Thanks for sharing. Added it.
Feel free to PR when you have something to add.

Cheers.
